# Generated by Django 3.2 on 2022-04-27 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20220420_0809'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factory',
            options={},
        ),
        migrations.RemoveField(
            model_name='factory',
            name='position',
        ),
        migrations.AddField(
            model_name='factory',
            name='data_order',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='data_order',
            field=models.DateField(blank=True, null=True),
        ),
    ]
