# Generated by Django 3.2 on 2021-09-28 08:37

from django.db import migrations
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_category_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=mptt.fields.TreeManyToManyField(blank=True, null=True, to='product.Category'),
        ),
    ]
