# Generated by Django 3.2 on 2021-10-09 16:00

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_bg',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='parent_bg',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product.category'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent_en',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product.category'),
        ),
        migrations.AddField(
            model_name='factory',
            name='description_bg',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='factory',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='factory',
            name='name_bg',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='factory',
            name='name_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_bg',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_bg',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='specification_bg',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='specification_en',
            field=models.TextField(null=True),
        ),
    ]
