# Generated by Django 3.2 on 2021-10-14 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('title_bg', models.CharField(max_length=250, null=True)),
                ('title_en', models.CharField(max_length=250, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('thumbnail', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('content', models.TextField()),
                ('content_bg', models.TextField(null=True)),
                ('content_en', models.TextField(null=True)),
                ('featured', models.BooleanField(default=False)),
                ('date_create', models.DateField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
