# Generated by Django 3.2 on 2021-09-28 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_rename_blogpost_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
