# Generated by Django 3.2 on 2021-10-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_services_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='content_bg',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='title_bg',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='title_en',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
